# Jekyll
markdown: kramdown
highlighter: "pygments"
permalink: /:title.html

# Site info
site:
  url: "https://bsidespei.ca"
  #favicon: "http://braziljs.org/favicon.ico"
  #googleanalytics: "UA-33656081-1"
  images:
    cover: "http://f.cl.ly/items/2X28422q1e3w0C2U1P3H/866591_24254643.jpg"
    facebook: "http://braziljs.org/img/fb-share.jpg"

subscribe_text: "Register now for free"
subscribe_url: "https://www.eventbrite.ca/e/bsidespei-tickets-26642284791"

# Active sections on the website
sections:
  about: true
  c4p: false
  location: true
  speakers: true
  schedule: true
  sponsors: true
  partners: true
  contact: false

# Contact section
contact_section:
   title: "Contact"
   text: "Contact us if you have any questions."
   contacts:
   -
     title: "Email"
     link: "mailto:your_email@domain"
   -
     title: "Facebook"
     link: "https://www.facebook.com/yourpage"
   email: "your_email@domain"
   twitter_url: "http://twitter.com/your_twitter"
   twitter_username: "@your_twitter"
   show_form: false
   form:
    action: "contato.php"
    name: "What's your name?"
    email: "What's your email?"
    message: "Write a message"
    send_button: "Send"

# Location section
location_section:
   title: "Location"

# Partners section
partners_section:
   title: "Partners"
   show_your_logo_here: true

# Schedule section
schedule_section:
   title: "Schedule"
   text: ""
   time: "Time"
   slot: "Slot"
   description: "Description"

# Speakers section
speakers_section:
   title: "Speakers"

# Sponsors section
sponsors_section:
   title: "Sponsors"
   show_your_logo_here: true